### ISSUE TITLE
ช่วยเพิ่มระบบให้ยศด้วยครับ

### ISSUE THREAD

**Issue by SadlyOfficical** [DearTanakorn/discord-vouchertopup#1]
แบบตามจำนวนเงินเติม ยศแบบกำหนดเวลาเช่า หรือ ยศถาวร
หมดเวลายศ มันจะลบยศนั้นออกทันที

**Comment by DearTanakorn** [comment]
ถ้าส่วนนี้อาจจะต้องหาคนมา contribute นะครับ ส่วนตัวเวลาว่างค่อนข้างน้อย ถ้าหากมีเวลาจะเข้ามาอัพเดตให้แน่นอนครับ (∩^o^)⊃━☆
